# Tool "markdown-link-check" is used to validate the links
# See https://www.npmjs.com/package/markdown-link-check
# See https://github.com/gaurav-nelson/github-action-markdown-link-check
# For the config file:
# See https://github.com/gaurav-nelson/github-action-markdown-link-check#custom-variables
# See https://github.com/tcort/markdown-link-check#config-file-format
name: check_validity_of_all_external_links
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Action
        uses: actions/checkout@v2
      - name: Setup Node runtimme
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install MLC
        run: npm install -g markdown-link-check
      - name: Run check
      - run: find . -name '*.md' -maxdepth 10 -exec markdown-link-check '{}' --config ./markdown-link-check_config.json
