# Tool "markdown-link-check" is used to validate the links
# See https://www.npmjs.com/package/markdown-link-check
# See https://github.com/gaurav-nelson/github-action-markdown-link-check
# For the config file:
# See https://github.com/gaurav-nelson/github-action-markdown-link-check#custom-variables
# See https://github.com/tcort/markdown-link-check#config-file-format
name: check_validity_of_all_external_links
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install -g markdown-link-check
      - run: markdown-link-check -V
      - run: find . -name "*.md" -exec markdown-link-check --verbose --config ./markdown-link-check_config.json "{}" \;
      - run: echo $?
