# Tool "markdown-link-check" is used to validate the links
# See https://www.npmjs.com/package/markdown-link-check
# See https://github.com/gaurav-nelson/github-action-markdown-link-check
name: check_validity_of_all_external_links
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Action
        uses: actions/checkout@v2
      - name: Run check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          max-depth: 10
          config-file: "./markdown-link-check_config.json"
      - run: curl -v --http1.1 -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" --head "https://gf.dev/cross-domain-policy-test"
